### ISSUE TITLE
Setting Up a Kanban Board for our project

### ISSUE THREAD

**Issue by mugberto** [mugberto/vacations-booking-back-end#44]
Link to our project: https://github.com/mugberto/vacations-booking-back-end/projects/1

Our group has five members:
- @themonster2015 
- @mugberto 
- @ShinobiWarior 
- @igorkol91 
- @danmainah

**Comment by rvvergara** [comment]
Hi team, 

In my opinion, your project is ready to be built!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
